dataset_params:
  modality: "PhenoBench"
  root: "dataset/PhenoBench/" # Path to the PhenoBench dataset
  fields: ["val"] # Not used for PhenoBench, but kept for structure

# --- VEGETATION DETECTOR PARAMETERS ---
plant_detector_params:
  # Using the robust Excess Green detector for RGB images
  name: "ExGDetector"
  params:
    # Tuned threshold from the UI to balance sensitivity and noise
    threshold: 0.25
    # Minimum number of pixels to be considered a plant component
    min_area: 50

# --- HOUGH TRANSFORM CROP ROW DETECTOR PARAMETERS ---
hough_detector_params:
  # Voting threshold for a line to be considered valid.
  # A higher value like 190 is good for clear rows.
  threshold: 120
  
  # Resolution of the Hough accumulator.
  step_theta: 3
  step_rho: 2

  # How much a line's angle can deviate from the dominant angle.
  angle_error: 5
  
  # Tolerance for clustering lines into a single crop row.
  clustering_tol: 3
  
  # Significance level for the uniformity test to discard images with no rows.
  uniform_significance: 0.10
  
  # Parameter to control angle reduction towards a central orientation. 1.0 means no reduction.
  theta_reduction_threshold: 1.00
  
  # Let the algorithm determine the angle automatically.
  theta_value: null

# --- SLIC PARAMETERS (if used for patch-based classification) ---
slic_params:
  percent: 0.005
  compactness: 20
  sigma: 1