name: SSLWeedMap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # --- Core Requirements ---
  - python=3.11
  - pip

  # --- PyTorch Stack with CUDA 12.1 ---
  # This is the correct way to request PyTorch with a specific CUDA version.
  # Conda will find the right Windows-compatible builds.
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  # --- Hugging Face Libraries ---
  - accelerate
  - datasets
  - transformers
  - huggingface_hub
  - tokenizers
  - safetensors

  # --- Data Science, ML, and Image Processing ---
  - pandas
  - numpy
  - scikit-learn
  - scikit-image
  - pyarrow
  - pillow
  - opencv  # Moved from pip to conda for better dependency handling
  - imageio
  - tifffile

  # --- Experimentation & Visualization ---
  - streamlit
  - wandb
  - optuna
  - torchmetrics
  - matplotlib
  - altair

  # --- Jupyter & Development Tools ---
  - jupyterlab
  - ipywidgets
  - tqdm
  - pyyaml
  - easydict
  - einops
  - colorlog
  - gitpython

  # --- Other Important Libraries ---
  - sqlalchemy
  - requests
  - fsspec

  # --- Pip-only dependencies ---
  # These are packages that were in the original pip section.
  - pip:
    - fastcore==1.5.48
    - lovely-numpy==0.2.12
    - lovely-tensors==0.1.15