# FILE: parameters/test/test_phenobench_latest.yaml

experiment:
  name: "PhenoBench Latest Ckpt Evaluation" # A descriptive name for your WandB run
  group: "Custom Model Tests"
  search: grid
  task: segmentation

parameters:
  seed: &seed [42]

  tracker:
    # You can keep these as is.
    ignored_files: ["*.bin,*.safetensors"]
    cache_directory: [wandb_cache]
    train_image_log_frequency: [20]
    val_image_log_frequency: [10]
    test_image_log_frequency: [10]
    tags: [[PhenoBench, RoWeeder-PseudoGT, Unsupervised]]

  # --- CRITICAL: Model Configuration ---
  model:
    name: [flat] # Use the same model architecture name as during training
    params:
      input_channels: &input_channels [['images']] # Must match training config
      fusion: [add]                               # Must match training config

      # --- This tells the model to build the *exact same architecture* as during training ---
      custom_hidden_sizes: [[16, 32, 64, 128]] 
      custom_num_heads: [[1, 2, 4, 8]]        # MUST MATCH the heads you used for training
      
      # --- This tells the model where to load its weights from ---
      checkpoint: ["wandb/run-20250630_163611-h4axbhue/files/best/pytorch_model.bin"]
  loss:
    class_weighting: [True]
    components:
      - focal:
          weight: 1.0
  # --- CRITICAL: Dataset Configuration ---
  dataset:
    root: ["dataset/PhenoBench"]
    gt_folder: ["dataset/generated/phenobench_config/pseudogt"]
    channels: *input_channels
    train_fields: [['train']]
    test_fields: [['val']]
    preprocess:
      resize: [512]
      mean: [[0.485, 0.456, 0.406]]
      std: [[0.229, 0.224, 0.225]]

  # --- CRITICAL: Dataloader Configuration ---
  dataloader:
    num_workers: [0] # Good for Windows
    batch_size: [10]  # Use a small batch size for testing to avoid memory issues

  # --- Metrics for Evaluation ---
  # These define what will be calculated and reported.
  train_metrics:
    JaccardIndex: &metric_params
      num_classes: [3]
      task: [multiclass]
      average: [macro]
    F1Score: *metric_params
  val_metrics:
    JaccardIndex: *metric_params
    F1Score: *metric_params
other_grids: []